name: sales-app
services:
  sales-app.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sales-app.database
    environment:
      SA_PASSWORD: "Password123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  sales-app.api:
    image: fitomedina/mdeis-m11-ga-ci-cd-backend:latest
    container_name: sales-app.api
    depends_on:
      sales-app.database:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sales-app.database;Database=products;User=sa;Password=Password123!;TrustServerCertificate=True;Encrypt=False;

  sales-app.seed:
    image: mcr.microsoft.com/mssql-tools
    container_name: sales-app.seed
    volumes:
      - ./database/seed.sql:/database/seed.sql
    depends_on:
      sales-app.database:
        condition: service_started
    entrypoint:  >
      bash -c '
      until /opt/mssql-tools/bin/sqlcmd -S sales-app.database -U sa -P Password123! -Q "SELECT 1" ; do
          sleep 2 ;
      done ;
      chmod 644 database/seed.sql ;
      /opt/mssql-tools/bin/sqlcmd -S sales-app.database -U sa -P Password123! -i /database/seed.sql ;
      '

  sales-app.client:
    image: fitomedina/mdeis-m11-ga-ci-cd-frontend:latest
    container_name: sales-app.client
    depends_on:
      - sales-app.api
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8080

volumes:
  sql_data:
