name: Backend CI/CD

on:
  push:
    branches:
      - feature
    paths:
      - SalesApp.Api/**

jobs:
  backend:
    name: Build & Publish Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore backend
        run: dotnet restore SalesApp.Api/SalesApp.Api.csproj

      - name: Run backend tests
        run: dotnet test --no-build SalesApp.Api/SalesApp.Api.csproj

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.KEY_M11_CI_CD }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: SalesApp.Api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mdeis-m11-ga-ci-cd-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mdeis-m11-ga-ci-cd-backend:${{ github.sha }}
